import runpod
import base64
import os
import tempfile
import time
import subprocess
import json

def handler(job):
    """
    RunPod Serverless Handler for NVIDIA PersonaPlex.
    """
    job_input = job['input']
    
    text_prompt = job_input.get("text_prompt", "You are a helpful AI assistant.")
    input_audio_b64 = job_input.get("input_audio_b64", None)
    
    if not input_audio_b64:
        return {"status": "error", "message": "No input_audio_b64 provided."}
        
    try:
        # Create temp files
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as in_tmp:
            in_tmp.write(base64.b64decode(input_audio_b64))
            input_audio_path = in_tmp.name
            
        output_audio_path = input_audio_path.replace(".wav", "_out.wav")
        output_json_path = input_audio_path.replace(".wav", "_out.json")
        prompt_txt_path = input_audio_path.replace(".wav", "_prompt.txt")
        
        with open(prompt_txt_path, "w") as f:
            f.write(text_prompt)
            
        # Run PersonaPlex Offline Inference
        # Based on NVIDIA's documentation: python -m moshi.offline --voice-prompt "NATF2.pt" ...
        cmd = [
            "python", "-m", "moshi.offline",
            "--voice-prompt", "NATF2.pt",
            "--text-prompt", prompt_txt_path,
            "--input-wav", input_audio_path,
            "--output-wav", output_audio_path,
            "--output-text", output_json_path
        ]
        
        # Execute the model inference (may take processing time)
        subprocess.run(cmd, check=True, cwd="/app/personaplex")
        
        # Read the output generated by PersonaPlex
        with open(output_audio_path, "rb") as audio_file:
            output_audio_b64 = base64.b64encode(audio_file.read()).decode('utf-8')
            
        transcript = ""
        if os.path.exists(output_json_path):
            with open(output_json_path, "r") as jf:
                transcript_data = json.load(jf)
                transcript = str(transcript_data)
                
        # Cleanup
        for path in [input_audio_path, output_audio_path, output_json_path, prompt_txt_path]:
            if os.path.exists(path):
                os.remove(path)

        return {
            "status": "success",
            "transcript": transcript,
            "response_audio_b64": output_audio_b64
        }
        
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

if __name__ == '__main__':
    runpod.serverless.start({"handler": handler})
